[theme]
primaryColor="#32c800"
backgroundColor="#252323"
secondaryBackgroundColor="#0a0a0a"
textColor="#fdfdfd"
font="serif"
language="toml"

--theme.primaryColor="#32c800"
--theme.backgroundColor="#252323"
--theme.secondaryBackgroundColor="#000000"
--theme.textColor="#fdfdfd"
--theme.font="serif"

