
[theme]
primaryColor="{#32c800}"
backgroundColor="{#FFFFFF}"
textColor="{serif}"
language="toml"

--theme.primaryColor="{#32c800}" 
--theme.backgroundColor="{#FFFFFF}" 
--theme.textColor="{serif}"



